### ISSUE TITLE
In install.php, don't assume host=localhost

### ISSUE THREAD

**Issue by MagicFab** [bemosior/PHPasswordPusher#33]

**Comment by bemosior** [comment]
@MagicFab I'm inclined to think that the short length and relative clarity of `install.php` lends itself to modification in cases where the database does not listen on the loopback interface. Do you have an idea of an alternative? Or do you think we need to include that in the documentation?

**Comment by MagicFab** [comment]
I agree, rephrasing, I think localhost should not be hardcoded (even if only a few lines below), but instead presented as a variable at the beginning. 

Re: documentation, no, the script should be self-documenting at least for this part!

**Comment by bemosior** [comment]
Ok, that's a reasonable approach!
