### ISSUE TITLE
Data at rest

### ISSUE THREAD

**Issue by dnichk** [bemosior/PHPasswordPusher#36]
How is the data protected when at rest? Is it encrypted in the database?

**Comment by bemosior** [comment]
Short answer: Secrets are encrypted, link UUIDs (used for credential lookup) are hashed.

Long answer:
1. The secret is grabbed from the user's POST and the encryption function is called: [code](https://github.com/bemosior/PHPasswordPusher/blob/master/pwpusher_public/pw.php#L91)
2. The secret is encrypted and then base64-encoded: [code](https://github.com/bemosior/PHPasswordPusher/blob/master/pwpusher_private/security.php#L15)
3. The ID is hashed and the result of the previous step is set up to be inserted into the database: [code](https://github.com/bemosior/PHPasswordPusher/blob/master/pwpusher_public/pw.php#L100)
4. And actually inserted: [code](https://github.com/bemosior/PHPasswordPusher/blob/develop/pwpusher_private/database.php#L19)


Disclaimer: I am not a security expert (or any expert, really). This solution has not been audited or pen-tested. However, I will assert that it's fundamentally better than sharing passwords over plain text or through other easily-accessible means.

I'll leave this issue open for now. Let me know if this request answers your question. :+1: for asking. I should probably compile the above into some sort of statement in the README.

**Comment by bemosior** [comment]
I should also mention that encrypted entries are evaluated for the necessity of their existence through a [scheduled task](https://github.com/bemosior/PHPasswordPusher/blob/develop/install.php#L21) run every minute, when a [new secret is inserted](https://github.com/bemosior/PHPasswordPusher/blob/master/pwpusher_private/database.php#L49), and when [a lookup occurs](https://github.com/bemosior/PHPasswordPusher/blob/master/pwpusher_private/database.php#L90). I'd certainly welcome any suggestions to make it more robust!

**Comment by MagicFab** [comment]
This would be very useful in a FAQ (or README at least).
