### ISSUE TITLE
MCRYPT_MODE_ECB is insecure.

### ISSUE THREAD

**Issue by bemosior** [bemosior/PHPasswordPusher#37]
`MCRYPT_MODE_ECB` will encrypt the same block the same way each time, meaning it is much more susceptible to attack (patterns can emerge). Furthermore, I discovered that the IV is completely ignored by ECB and the same initialization vector needs to be used for decryption, so the current implementation is both misleading and useless. 

I intend to switch to `MCRYPT_MODE_CBC` and store the IV at the beginning of the encrypted string, as shown in the [mcrypt_encrypt documentation](http://php.net/manual/en/function.mcrypt-encrypt.php#example-885).

**Comment by vaindil** [comment]
It [looks like](http://www.daemonology.net/blog/2009-06-11-cryptographic-right-answers.html) `ctr` is actually the best mode to use (naturally, [it's not documented by PHP](https://stackoverflow.com/questions/5108408/php-mcrypt-which-mode)). I'll look into implementing this.

**Comment by vaindil** [comment]
(marked as a bug due to the nature of the project--if we're trying to make it as secure as possible, a security problem is definitely a bug in my mind)

**Comment by bemosior** [comment]
An interesting problem in the rewrite, Laravel 5.1 only seems to support `AES-256-CBC`. I'll take a shot at implementing `CTR` in the v1 branch, though.

**Comment by bemosior** [comment]
I'm completely open to reconsidering CTR, but I think I've been successfully scared into sticking to CBC. http://sockpuppet.org/blog/2013/07/22/applied-practical-cryptography/

CBC is more likely to be robust if used incorrectly (I'm not a cryptography expert, therefore my confidence in any implementation is very low), and I don't have appropriate mechanisms in place to store a counter for the IVs, which would be necessary for CTR. I feel most confident in my implementation of CBC, so that's what I've pushed up.

I'll close this for now, but feel free to reopen in order to have more discussion!
