### ISSUE TITLE
v2 Planning

### ISSUE THREAD

**Issue by bemosior** [bemosior/PHPasswordPusher#38]
With the current project layout, making changes can be a frustrating process. I would like to shift towards a rewrite under a more standard framework (I'm biased towards Laravel v5.0).

We could have standard support for:
* [Dependency Management](http://laravel.com/docs/5.0#install-composer) (via Composer)
* [Encryption](http://laravel.com/docs/5.0/encryption)
* [Translations](http://laravel.com/docs/5.0/localization)
* [Error Handling](http://laravel.com/docs/5.0/errors)
* [More Databases](http://laravel.com/docs/5.0/database)

**Comment by bemosior** [comment]
Laravel v5.0 does require a minimum PHP of 5.4. My intention would be for more constrained systems to utilize PHPasswordPusher v1. We could continue to maintain both versions independently.

**Comment by bemosior** [comment]
Parallel development has begun in the `develop-v2` branch.

**Comment by bemosior** [comment]
I started with Laravel v5.1, which does have a PHP requirement of >=5.5.9, which means those constrained to lesser PHP versions will be stuck with the v1 codebase.

I don't want this to be one of those situations where I've made an arbitrary decision that has more serious consequences later... My opinion has changed here. I want to write better software, and right now that means I would like to use modern tools that enable better practices.

If anyone has concerns about this decision, please speak up. It's easier to redirect an effort at the beginning than to wait until halfway through and say "I wish you hadn't done that."

**Comment by vaindil** [comment]
I completely agree with the idea. No problem maintaining an old version that may get feature updates every now and then, but in general will just be maintained for people who can't upgrade. I want to leverage the latest stable packages that are available and go from there.

**Comment by bemosior** [comment]
Ok, thanks for helping me work through this issue!
