### ISSUE TITLE
Links expire prematurely.

### ISSUE THREAD

**Issue by dnichk** [bemosior/PHPasswordPusher#40]
I have a set-up, and I am not sure if I did something wrong, but say for example set the expiration to be 5 days and 5 views, but then the link is not viewed say for 40 minutes - the link comes up a "expired".

Did I miss something in the scheduling requirements or the like?

**Comment by vaindil** [comment]
This was just fixed in #39. We'll push to the master branch in the near future, there are a few things to be updated. Alternatively, you can [make the change yourself](https://github.com/bemosior/PHPasswordPusher/commit/37a06676bd62baf9cfa0b541d6e85e5dceac6841), it's a quick fix.

Sorry about that!

**Comment by dnichk** [comment]
Awesome service. Thanks for the quick fix. I'll manually do it to get the app back in use. 
What the best way to update future releases? Just replace files?


Regards. 

Dustin Krysak
Sokin Systems

Need help? 
Please eMail: support@sokinsystems.zendesk.com




On Tue, Jul 7, 2015 at 10:33 AM -0700, "Steven Hall" <notifications@github.com> wrote:












This was just fixed in #39. We'll push to the master branch in the near future, there are a few things to be updated. Alternatively, you can make the change yourself, it's a quick fix.



Sorry about that!

**Comment by bemosior** [comment]
Thanks @vaindil!

@dnichk Unfortunately we don't have a great upgrade path/process in place yet. Copying over files is the best way for now.
