### ISSUE TITLE
Flash Support

### ISSUE THREAD

**Issue by vaindil** [bemosior/PHPasswordPusher#41]
We currently use [ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard) to allow automatic copy/pasting of the secret link, but is this something we want to continue to support? I ask because some of the major players are moving towards blocking it.

 * Facebook's chief of security [said](http://www.theguardian.com/technology/2015/jul/14/facebook-end-adobe-flash-firefox-blocks-hacking) that it's time for Adobe to publicly announce Flash's end-of-life.
 * Mozilla [has gone so far](http://www.bbc.com/news/technology-33520935) as to block ALL versions of Flash outright at the moment.
 * Google [said](http://arstechnica.co.uk/information-technology/2015/06/google-chrome-will-soon-intelligently-block-auto-playing-flash-ads/) Chrome will automatically block some auto-playing Flash ads in upcoming versions (for battery reasons, but it's still happening).

Knowing this, perhaps it's time to move to a different scheme, such as auto-selecting the text (or a button to select the text) and having the user manually copy, since there's no other way that I know of to allow a user to copy something like we currently do.

**Comment by bemosior** [comment]
:+1: Having auto-copy behavior is kind of unintuitive anyway. Auto-selecting the text seems a reasonable approach.

**Comment by dnichk** [comment]
I say kill it. It's not overly hard to select text anyways. :)

**Comment by vaindil** [comment]
Fixed with [clipboard.js](https://github.com/zenorocha/clipboard.js) in d7e7514.
