### ISSUE TITLE
Query : Best way to update PHPasswordPusher (Sorry - not a new issue)

### ISSUE THREAD

**Issue by macnetdaemon** [bemosior/PHPasswordPusher#43]
Benjamin (et al),

    Please let us know the best way to submit a quick query like this in the future. I hate to fill your dev. space with queries that should be sent elsewhere.  

    What is the best way to update files from this project? Download the entire zip or individual files as they become available?

Thanks for your time,
--pw

**Comment by bemosior** [comment]
Given the small scale of this project, it's absolutely ok to use the issues for questions! 

I think someone else asked this recently, but I can't seem to find it. The unfortunate truth is that when I originally developed the project, I had not considered that people would be using the software let alone be needing to update it. As a result, this process is harder than it should be.

After thinking about it again, it's probably best to save a backup of the existing installation, pull down a fresh zip, and adjust the individual configuration items to match what you had in the previous installation. This shouldn't be done lightly, though, as some of our recent development changes (particularly surrounding data encryption) could break existing data. I think if the update ceiling is [v1.1.0](https://github.com/bemosior/PHPasswordPusher/releases/tag/v1.1.0) and not current development, you would be ok.

**Comment by macnetdaemon** [comment]
Thanks Benjamin,

    We are actually using this project in our district. It's proven very handy behind our firewall. Your work is appreciated.

Many thanks,
Paul

**Comment by bemosior** [comment]
Great to hear! Keep an eye out for the next major versions. :) Many great improvements coming about in the rewrite.

Feel free to reply back if you run into any specific issues. We can reopen and take a look.
