### ISSUE TITLE
Release Planning (breaking changes in the v1 branch)

### ISSUE THREAD

**Issue by bemosior** [bemosior/PHPasswordPusher#44]
@vaindil #43 raises an interesting question. Technically speaking, our recent changes on the v1 branch would break many existing installations. Per [semver](http://semver.org/), our changes not being "backwards compatible" excludes them from being released under a minor version. That means our next release of the code currently in the v1 branch should probably be as v2, which pushes the rewrite with Laravel to v3. Am I overthinking this?

**Comment by bemosior** [comment]
I've pushed the rewrite to `develop-v3`, since I'm pretty sure this is what we need to do version-wise.

As far as integration of the rewrite, we either need to isolate legacy development on a release branch or consider bumping the rewrite into its own project, since there's no common ancestry (PHPasswordPusher is a goofy name, too).

In the case of the former, we could rename `master` to `master-v2`, rename `develop` to `develop-v2`, and make a copy of `develop-v3` as `master-v3`. I struggled through a number of different branching ideas, and this is the most clear and consistent I could find. Suggestions are welcome!

In the case of the latter, the rewrite goes into its own project, and this problem goes away entirely.

**Comment by bemosior** [comment]
Much of the external advice I've been getting on this point is to push the rewrite into its own repository, since there's no common ancestry. I think I might do that then, since that allows us to maintain both version of the project independently. PHPasswordPusher can be for those who are confined to using older versions of PHP, and whatever the other repository is can sport the latest and greatest.

**Comment by vaindil** [comment]
I think that makes a lot of sense. I can work on/push the intermediate changes to v2 (and keep that on a branch here with a wiki article for migrating from v1 to v2), then the new one (v3) as its own repo sounds good.

**Comment by bemosior** [comment]
Ok great. We can keep the typical `develop`/`master` branching strategy then for v2 in this repository, using tags to distinguish the v1/v2 releases.

**Comment by bemosior** [comment]
Thus, [Agrippa](https://github.com/unicalabs/agrippa) is born (name based on [the art of William Gibson](https://en.wikipedia.org/wiki/Agrippa_(A_Book_of_the_Dead)) by the same name).

I'll open another issue about documentation, specifically to direct those with constrained environments to this project and those who can adopt the latest version of PHP to Agrippa.
